#include "HardwareProfile.h"
#include <stdio.h>
const unsigned char GapXY[12][2]=
{
	108,70,
	116,70,
	124,70,
	132,70,

	108,108,
	116,108,
	124,108,
	132,108,

	108,148,
	116,148,
	124,148,
	132,148,
};
void SetMode_ShowGapInit(void)
{
	unsigned char i,x,t1,t2;
	unsigned int y;
	SetMode=SetMode_ShowGap;
	NoWirelessRxTick=SystemTick;
	Display_ShowPic(9);
	Display_SetTxtColor(1);
	SetIndex=0;
	//SetRow=0;
	FrashTick=SystemTick;
	gFlags.bFrashShow=1;
	if(ROMParams.TimeSpan1==0xffff)
	{		
		for(i=0;i<4;i++)
		{
			SetNum[i]='*';			
			Display_ShowTxt(0x01,GapXY[0][0],GapXY[0][1],SetNum,4);
		}
	}
	else
	{
		sprintf(DisplayLine,"%04u",ROMParams.TimeSpan1);
		Display_ShowTxt(0x01,GapXY[0][0],GapXY[0][1],DisplayLine,4);
		for(i=0;i<4;i++)
			SetNum[i]=DisplayLine[i];
	}
	if(ROMParams.TimeSpan2==0xffff)
	{		
		for(i=0;i<4;i++)
		{
			SetNum[i+4]='*';			
			Display_ShowTxt(0x01,GapXY[4][0],GapXY[4][1],&SetNum[4],4);
		}
	}
	else
	{
		sprintf(DisplayLine,"%04u",ROMParams.TimeSpan2);
		Display_ShowTxt(0x01,GapXY[4][0],GapXY[4][1],DisplayLine,4);
		for(i=0;i<4;i++)
			SetNum[i+4]=DisplayLine[i];
	}
	if(ROMParams.TimeSpan3==0xffff)
	{		
		for(i=0;i<4;i++)
		{
			SetNum[i+8]='*';			
			Display_ShowTxt(0x01,GapXY[8][0],GapXY[8][1],&SetNum[8],4);
		}
	}
	else
	{
		sprintf(DisplayLine,"%04u",ROMParams.TimeSpan3);
		Display_ShowTxt(0x01,GapXY[8][0],GapXY[8][1],DisplayLine,4);
		for(i=0;i<4;i++)
			SetNum[i+8]=DisplayLine[i];
	}
}
void SetMode_ShowGapProc(void)
{
  	unsigned char keynum,x,i;
 	if(GetDeltaTick(FrashTick)>4)
 	{
 		gFlags.bFrashShow=!gFlags.bFrashShow;
 		FrashTick=SystemTick;
		if(gFlags.bFrashShow)
			DisplayLine[0]=SetNum[SetIndex];
		else
			DisplayLine[0]=' ';
		Display_ShowTxt(0x01,GapXY[SetIndex][0],GapXY[SetIndex][1],DisplayLine,1); 		
 	}
 	if(KeyPollCheck()==1)
 	{			
 		if(KeyValue.u16==Key_ENT)
 		{
 			x=0;
			for(i=0;i<4;i++)
			{
				if(SetNum[i]=='*')
					x=1;
			}
			if(x==1)
				ROMParams.TimeSpan1=0xffff;
			else
			{
				ROMParams.TimeSpan1=(SetNum[0]-'0')*1000;
				ROMParams.TimeSpan1+=(SetNum[1]-'0')*100;
				ROMParams.TimeSpan1+=(SetNum[2]-'0')*10;
				ROMParams.TimeSpan1+=(SetNum[3]-'0');
			}
			x=0;
			for(i=0;i<4;i++)
			{
				if(SetNum[i+4]=='*')
					x=1;
			}
			if(x==1)
				ROMParams.TimeSpan2=0xffff;
			else
			{
				ROMParams.TimeSpan2=(SetNum[4]-'0')*1000;
				ROMParams.TimeSpan2+=(SetNum[5]-'0')*100;
				ROMParams.TimeSpan2+=(SetNum[6]-'0')*10;
				ROMParams.TimeSpan2+=(SetNum[7]-'0');
			}
			x=0;
			for(i=0;i<4;i++)
			{
				if(SetNum[i+8]=='*')
					x=1;
			}
			if(x==1)
				ROMParams.TimeSpan3=0xffff;
			else
			{
				ROMParams.TimeSpan3=(SetNum[8]-'0')*1000;
				ROMParams.TimeSpan3+=(SetNum[9]-'0')*100;
				ROMParams.TimeSpan3+=(SetNum[10]-'0')*10;
				ROMParams.TimeSpan3+=(SetNum[11]-'0');
			}
			FRAM_SaveROMParams();
			Display_ShowPic(12);
			SettingTick=SystemTick;
			while(1)
			{
				if(GetDeltaTick(SettingTick)>30)
				{
					WorkMode_SettingInit();
					return;
				}
			}
 		}
 		else if(KeyValue.u16==Key_Left)
 		{
			Display_ShowTxt(0x01,GapXY[SetIndex][0],GapXY[SetIndex][1],&SetNum[SetIndex],1); 
 			if(SetIndex==0)
				SetIndex=11;
			else
				SetIndex--;
 		}	
		else if(KeyValue.u16==Key_Right)
		{
			Display_ShowTxt(0x01,GapXY[SetIndex][0],GapXY[SetIndex][1],&SetNum[SetIndex],1); 
			if(SetIndex==11)
				SetIndex=0;
			else
				SetIndex++;
		}
		else if(KeyValue.u16==Key_TAB || KeyValue.u16==Key_Down)
		{
			Display_ShowTxt(0x01,GapXY[SetIndex][0],GapXY[SetIndex][1],&SetNum[SetIndex],1); 
			SetIndex=SetIndex+4;
			if(SetIndex>11)
				SetIndex=SetIndex-12;
		}
		else if(KeyValue.u16==Key_Up)
		{
			Display_ShowTxt(0x01,GapXY[SetIndex][0],GapXY[SetIndex][1],&SetNum[SetIndex],1); 
			if(SetIndex<4)
				SetIndex=SetIndex+8;
			else
				SetIndex=SetIndex-4;
		}  	
		else if(KeyValue.u16==Key_Start)
		{
			gFlags.bFrashShow=0;
			FrashTick=SystemTick-10;
			SetNum[SetIndex]='*';  		
			Display_ShowTxt(0x01,GapXY[SetIndex][0],GapXY[SetIndex][1],&SetNum[SetIndex],1); 
			if(SetIndex==11)
				SetIndex=0;
			else
				SetIndex++;
		}
  		else
  		{
  			keynum=GetKeyNum();
  			if(keynum!=0xff)//ÊÇÊý×Ö
  			{
  				gFlags.bFrashShow=0;
  				FrashTick=SystemTick-10;
				SetNum[SetIndex]=keynum+'0';  
				Display_ShowTxt(0x01,GapXY[SetIndex][0],GapXY[SetIndex][1],&SetNum[SetIndex],1); 
				if(SetIndex==11)
					SetIndex=0;
				else
					SetIndex++;
  			}
			else
			{
				CommonKeyFun();
			}
 		}
 	}
}
